language: java
addons:
  sonarcloud:
    organization: "nareshkumar-h-github"
    token:
      secure: b3386aea9ea5403d460f0ff7a0877abc0f4075d1
 script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar